{'Package': 'python3-django-dbconn-retry', 'Source': 'python-django-dbconn-retry', 'Version': '0.1.5-1', 'Installed-Size': '37', 'Maintainer': 'Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>', 'Architecture': 'all', 'Depends': ['python3-django', ['python3:any', '>=', '3.3.2-2~']], 'Description': 'reconnect on a failed database (Python3 version)', 'Homepage': 'https://github.com/jdelic/django-dbconn-retry/', 'Description-md5': 'e6f9867f49ff9821aa4e414064f0370a', 'Section': 'python', 'Priority': 'optional', 'Filename': 'pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.5-1_all.deb', 'Size': '8528', 'SHA256': 'aeb1f2c322079232b58cc5284a477144410a6c92453083e262d7301122c13ec9'}